### ISSUE TITLE
[PE-D][Tester B] Help for individual commands not shown for all commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#255] opened 2024-04-05 19:07 UTC
## Description
![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/acfc72e0-83ea-4e74-b618-4b6d4a9eee52.png)

Some commands do not display the help message:
1. `help help` - displays entire help box
2. `exit help` - exits the app

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: RyanNgWH/ped#5

**Comment by appleraincoat** [comment] 2024-04-06 09:54
Update ug to mention which commands have the help

**Comment by UdhayaShan1** [comment] 2024-04-06 10:00
Duplicate of #271 will close

**Closed by UdhayaShan1** 2024-04-06 10:00 UTC
