### ISSUE TITLE
[PE-D][Tester D] Inaccurate field constraints

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#257] opened 2024-04-05 19:49 UTC
According to field constraints and error messages, the email `a+_b@a.asdf` should be valid

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: cocoanautz/ped#1

**Comment by UdhayaShan1** [comment] 2024-04-06 09:56
FF

**Comment by jyztintan** [comment] 2024-04-06 15:11
i do not understand how this is a bug. 



> a+_b@a.asdf

i believe this is a valid email..
https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1

**Comment by appleraincoat** [comment] 2024-04-07 05:46
This is a duplicate bug, similar to issue #264 
To address your concerns @jyztintan , this is an issue with the our email regex where consecutive special characters are not accepted. Since the email contains "+_", which is valid, our app does not accept it.

**Comment by UdhayaShan1** [comment] 2024-04-07 05:50
Yep its carried over bad regex from AB3

**Comment by UdhayaShan1** [comment] 2024-04-09 07:02
Duplicate of #264 will close

**Closed by UdhayaShan1** 2024-04-09 07:02 UTC
Labels: type.FeatureFlaw
